# Generated by Django 5.2.2 on 2025-06-10 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_email', models.EmailField(max_length=254)),
                ('filename', models.CharField(max_length=255)),
                ('file', models.BinaryField()),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('fraud_score', models.FloatField(blank=True, null=True)),
                ('verdict', models.CharField(default='Pending', max_length=50)),
            ],
        ),
    ]
